### ISSUE TITLE
La anidación de etiquetas HTML debe ser correcta

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/proyecto2024-bono-bocco#8]
En HTML, colocar un <button> dentro de un <a> no es correcto según las especificaciones del estándar HTML . Esto se debe a que <a> es un elemento en línea y no se espera que contenga elementos de control de formulario, como <button>, que tienen un comportamiento interactivo específico.

https://github.com/UCC-LabCompu2/proyecto2024-bono-bocco/blob/87a819b24597734a2a776fe3379c74f8439b7f7a/FIN.html#L17

https://github.com/UCC-LabCompu2/proyecto2024-bono-bocco/blob/87a819b24597734a2a776fe3379c74f8439b7f7a/FIN.html#L39

https://github.com/UCC-LabCompu2/proyecto2024-bono-bocco/blob/87a819b24597734a2a776fe3379c74f8439b7f7a/COLOR.html#L18

https://github.com/UCC-LabCompu2/proyecto2024-bono-bocco/blob/87a819b24597734a2a776fe3379c74f8439b7f7a/COLOR.html#L28

https://github.com/UCC-LabCompu2/proyecto2024-bono-bocco/blob/87a819b24597734a2a776fe3379c74f8439b7f7a/COLOR.html#L30

https://github.com/UCC-LabCompu2/proyecto2024-bono-bocco/blob/87a819b24597734a2a776fe3379c74f8439b7f7a/COLOR.html#L32

https://github.com/UCC-LabCompu2/proyecto2024-bono-bocco/blob/87a819b24597734a2a776fe3379c74f8439b7f7a/COLOR.html#L34

https://github.com/UCC-LabCompu2/proyecto2024-bono-bocco/blob/87a819b24597734a2a776fe3379c74f8439b7f7a/COLOR.html#L39

https://github.com/UCC-LabCompu2/proyecto2024-bono-bocco/blob/87a819b24597734a2a776fe3379c74f8439b7f7a/LLANTAS.html#L17

https://github.com/UCC-LabCompu2/proyecto2024-bono-bocco/blob/87a819b24597734a2a776fe3379c74f8439b7f7a/LLANTAS.html#L25

https://github.com/UCC-LabCompu2/proyecto2024-bono-bocco/blob/87a819b24597734a2a776fe3379c74f8439b7f7a/LLANTAS.html#L27

https://github.com/UCC-LabCompu2/proyecto2024-bono-bocco/blob/87a819b24597734a2a776fe3379c74f8439b7f7a/LLANTAS.html#L29

https://github.com/UCC-LabCompu2/proyecto2024-bono-bocco/blob/87a819b24597734a2a776fe3379c74f8439b7f7a/LLANTAS.html#L31

https://github.com/UCC-LabCompu2/proyecto2024-bono-bocco/blob/87a819b24597734a2a776fe3379c74f8439b7f7a/LLANTAS.html#L38

https://github.com/UCC-LabCompu2/proyecto2024-bono-bocco/blob/87a819b24597734a2a776fe3379c74f8439b7f7a/index.html#L27-L28

https://github.com/UCC-LabCompu2/proyecto2024-bono-bocco/blob/87a819b24597734a2a776fe3379c74f8439b7f7a/index.html#L33

**Comment by NicolasBono** [comment]
una pregunta a esto lo resolvemos de esta forma aplicando el evento onclick

button id="Colorindex" onclick="location.href='COLOR.html'" COLOR /button"
(me borra el mayor menor =)
